global:
  configMapName: cloudbank-config
  rabbitmqAddress: rabbitmq-service
  activeProfile: prod
  configServerImport: configserver:http://config-server-service:8010
  postgresR2BCUrl: r2dbc:postgresql://postgres-service:5432
  gitSecretName: github-secret
  gitPassword:
