global:
  # How frequently to scrape targets by default.
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'cloudbank'
    metrics_path: /actuator/prometheus
    eureka_sd_configs:
      - server: http://eurekaServer:8011/eureka
  - job_name: 'cloudbank-config'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['configServer:8010']
  - job_name: 'cloudbank-eureka'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eurekaServer:8011']
