apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.applicationLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationLabel }}
    spec:
      containers:
        - name: {{ .Values.applicationLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: RABBIT_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMapName }}
                  key: RABBIT_ADDRESSES
            - name: RABBIT_USER
              value: guest
            - name: RABBIT_PASSWORD
              value: guest
            - name: STORAGE_TYPE
              value: mem
          ports:
            - containerPort: {{ .Values.service.port }}
