target:
  eurekaHost: eureka-server-service:8011
  configServerHost: config-server-service:8010

applicationName: prometheus
applicationLabel: prometheus

replicaCount: 1

image:
  repository: prom/prometheus
  tag: v2.36.2

service:
  type: NodePort
  port: 9090
  targetPort: 9090
