apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
spec:
  selector:
    app: {{ .Values.deploymentLabel }}
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    name: internal
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  - protocol: TCP
    name: web
    port: {{ .Values.service.port2 }}
    targetPort: {{ .Values.service.targetPort2 }}
