apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudbank-config
data:
  RABBIT_ADDRESSES: rabbitmq-service
  SPRING_PROFILES_ACTIVE: prod
  SPRING_RABBITMQ_HOST: rabbitmq-service
  SPRING_CONFIG_IMPORT: configserver:http://config-server-service:8010
  DB_POSTGRES_URL: r2dbc:postgresql://postgres-service:5432
