apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
      - name: loans
        image: andychentw/loans:latest
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: cloudbank-config
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: cloudbank-config
                key: SPRING_CONFIG_IMPORT
          - name: DB_POSTGRES_URL
            valueFrom:
              configMapKeyRef:
                name: cloudbank-config
                key: DB_POSTGRES_URL
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: loans-service
spec:
  selector:
    app: loans
  type: ClusterIP  
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
