{{- define "common.deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.applicationLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationLabel }}
    spec:
      containers:
        - name: {{ .Values.applicationLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            {{- if .Values.profile_enabled }}
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMapName }}
                  key: SPRING_PROFILES_ACTIVE
            {{- end }}
            {{- if .Values.configImport_enabled }}
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMapName }}
                  key: SPRING_CONFIG_IMPORT
            {{- end }}
            {{- if .Values.postgresUrl_enabled }}
            - name: DB_POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: cloudbank-config
                  key: DB_POSTGRES_URL
            {{- end }}
            {{- if .Values.rabbitmqHost_enabled }}
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMapName }}
                  key: SPRING_RABBITMQ_HOST
            {{- end }}
            {{- if .Values.gitPassword_enabled }}
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.gitSecretName }}
                  key: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
{{- end }}
