{{- define "common.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.gitSecretName }}
type: Opaque
data:
  SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: {{ .Values.global.gitPassword }}
{{- end }}
