applicationName: config-server
applicationLabel: config-server

replicaCount: 2

image:
  repository: andychentw/bank-config
  tag: latest

service: 
  type: ClusterIP
  port: 8010
  targetPort: 8010

profile_enabled: false
configImport_enabled: false
postgresUrl_enabled: false
rabbitmqHost_enabled: true
gitPassword_enabled: true
