applicationName: rabbitmq
applicationLabel: rabbitmq

replicaCount: 1

image:
  repository: rabbitmq
  tag: 3.10-management

service: 
  type: NodePort
  port: 15672
  targetPort: 15672
  port2: 5672
  targetPort2: 5672
